spring:
  application:
    name: red
  datasource:
    username: ${RED_DB_USER}
    password: ${RED_DB_PASSWORD}
    url: jdbc:postgresql://${RED_DB_HOST}:${RED_DB_PORT}/${RED_DATABASE}
  jpa:
    show-sql: true
    generate-ddl: true
server:
  shutdown: GRACEFUL

management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health

